package com.mohaberabi.jethabbit.core.presentation.design_system.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF000000)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF262626)
val onPrimaryContainerLight = Color(0xFFB1B1B1)
val secondaryLight = Color(0xFF5E5E5E)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE6E6E6)
val onSecondaryContainerLight = Color(0xFF4A4A4A)
val tertiaryLight = Color(0xFF000000)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF262626)
val onTertiaryContainerLight = Color(0xFFB1B1B1)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF9F9F9)
val onBackgroundLight = Color(0xFF1B1B1B)
val surfaceLight = Color(0xFFF9F9F9)
val onSurfaceLight = Color(0xFF1B1B1B)
val surfaceVariantLight = Color(0xFFEBE0E1)
val onSurfaceVariantLight = Color(0xFF4C4546)
val outlineLight = Color(0xFF7E7576)
val outlineVariantLight = Color(0xFFCFC4C5)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF303030)
val inverseOnSurfaceLight = Color(0xFFF1F1F1)
val inversePrimaryLight = Color(0xFFC6C6C6)

